.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. thalercoin_qt test_thalercoin_qt
clean: FORCE
	$(MAKE) -C .. thalercoin_qt_clean test_thalercoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_thalercoin_qt_check
thalercoin-qt thalercoin-qt.exe: FORCE
	 $(MAKE) -C .. thalercoin_qt
